// eslint-disable-next-line @typescript-eslint/no-unused-vars
const CollectibleTypePurgatory = {
  SPRINKLER_HEAD : Isaac.GetItemIdByName("Sprinkler Head"),
  MEMORY_LEAK : Isaac.GetItemIdByName("Memory Leak"),
  WEIGHTED_D1 : Isaac.GetItemIdByName("Weighted D1"),
  WEIGHTED_D4 : Isaac.GetItemIdByName("Weighted D4"),
  WEIGHTED_D6 : Isaac.GetItemIdByName("Weighted D6"),
  WEIGHTED_ETERNAL_D6 : Isaac.GetItemIdByName("Weighted Eternal D6"),
  WEIGHTED_D7 : Isaac.GetItemIdByName("Weighted D7"),
  WEIGHTED_D8 : Isaac.GetItemIdByName("Weighted D8"),
  WEIGHTED_D10 : Isaac.GetItemIdByName("Weighted D10"),
  WEIGHTED_D12 : Isaac.GetItemIdByName("Weighted D12"),
  WEIGHTED_D20 : Isaac.GetItemIdByName("Weighted D20"),
  WEIGHTED_D100 : Isaac.GetItemIdByName("Weighted D100"),
  WEIGHTED_SPINDOWN_DICE : Isaac.GetItemIdByName("Weighted Spindown Dice"),
  TISSUE_BOX : Isaac.GetItemIdByName("Tissue Box"),
  WAKE_ME_UP : Isaac.GetItemIdByName("Wake Me Up"),
  SUPERBIA : Isaac.GetItemIdByName("Superbia"),
  INVIDIA : Isaac.GetItemIdByName("Invidia"),
  IRA : Isaac.GetItemIdByName("Ira"),
  ACEDIA : Isaac.GetItemIdByName("Acedia"),
  AVARITIA : Isaac.GetItemIdByName("Avaritia"),
  GULA : Isaac.GetItemIdByName("Gula"),
  LUXURIA : Isaac.GetItemIdByName("Luxuria"),
} as const
